depromeet/street-drop-iOS

README.md

close #1 
- 애플 소셜 로그인 추가
- ~~ ~~해라

✨ 애플 소셜 로그인 추가

---

CODE_CONVENTION.md

📝 코드 컨벤션 작성

---

StreetDrop/NetworkManagerTest/NetworkManagerTest.swift
StreetDrop/StreetDrop.xcodeproj/project.pbxproj
StreetDrop/StreetDrop/Data/DataMapping/Community/CommunityResponseDTO.swift
StreetDrop/StreetDrop/Network/NetworkManager.swift
StreetDrop/StreetDrop/Network/NetworkService.swift

close #27
- 커뮤니티 API 구현
- Stub을 이용한 API 테스트 구현
- NetworkManagerTest 파일에서 test_getCommunity_success() 테스트 실행하기

✨ 커뮤니티 API 구현

---

StreetDrop/StreetDrop.xcodeproj/project.pbxproj
StreetDrop/StreetDrop/Presentation/MyPage/View/InfoTableViewCell.swift
StreetDrop/StreetDrop/Presentation/MyPage/View/MyPageViewController.swift
StreetDrop/StreetDrop/Presentation/MyPage/ViewModel/MyPageViewModel.swift
StreetDrop/StreetDrop/Presentation/SearchingMusicScene/View/SearchingMusicViewController.swift
StreetDrop/StreetDrop/Util/Constant/MyPageInfo.swift

close #88 
- 마이페이지 화면 및 기능 구현
```swift
class SceneDelegate: UIResponder, UIWindowSceneDelegate {
var window: UIWindow?
func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
guard let windowScene = (scene as? UIWindowScene) else { return }
window = UIWindow(frame: UIScreen.main.bounds)
window?.windowScene = windowScene
let navigationController = UINavigationController(
rootViewController: MyPageViewController(viewModel: DefaultMyPageViewModel())
)
window?.rootViewController = navigationController
window?.makeKeyAndVisible()
}
}
```

✨마이페이지 화면 및 기능 구현

---

StreetDrop/StreetDrop/Data/DataMapping/MusicCountByDong/MusicCountByDongResponseDTO+Mapping.swift
StreetDrop/StreetDrop/Network/NetworkService.swift
StreetDrop/StreetDrop/Presentation/MainScene/LocationManager/LocationManager.swift
StreetDrop/StreetDrop/Presentation/MainScene/Model/Entity/MusicCountEntity.swift
StreetDrop/StreetDrop/Presentation/MainScene/View/MainViewController.swift
StreetDrop/StreetDrop/Presentation/MainScene/ViewModel/MainViewModel.swift

close #110 
- 현재 위치 갱신 로직 추가
- 현재 위치 버튼(1차 앱스토어에선 홈버튼) 클릭 시, 카메라 및 사용자오버레이 위치 갱신

✨현재 위치 버튼 기능 추가

---

StreetDrop/StreetDrop/Presentation/MainScene/ViewModel/MainViewModel.swift

close #121 
메인화면에서 api로 주소 가져올 때, 전달값에도 반영되도록 
메인화면 address 프로퍼티에도 가져온 주소 값 할당

Feature/드랍화면 주소 안들어오는 문제 해결

---

StreetDrop/StreetDrop/Presentation/MainScene/View/MainViewController.swift
StreetDrop/StreetDrop/Presentation/MainScene/ViewModel/MainViewModel.swift

close #129 
- 500미터 반경내인지 여부 로직 추가
- 500m 반경 내 POI 마커만 클릭 시, 상세정보 API를 호출하여 반경 내 음악들의 다이얼 UI가 나타나도록 구현

✨500m 반경 내 POI 마커만, 클릭 시, 상세정보 API를 호출하여 반경 내 음악들의 다이얼 UI가 나타나도록 구현

---

StreetDrop/StreetDrop/Presentation/CommunityView/View/CommunityViewController.swift
StreetDrop/StreetDrop/Presentation/MainScene/View/MainViewController.swift
StreetDrop/StreetDrop/Presentation/MainScene/ViewModel/MainViewModel.swift
StreetDrop/StreetDrop/Resource/Info.plist

close #133 
- 먼저 유튜브 뮤직앱 Urlschme 이동하도록 시도하고, 실패 시 유튜브뮤직 웹사이트 url으로 이동

✨먼저 유튜브 뮤직앱 Urlschme 이동하도록 시도하고, 실패 시 유튜브뮤직 웹사이트 url으로 이동

---

StreetDrop/StreetDrop/Presentation/MainScene/LocationManager/LocationManager.swift
StreetDrop/StreetDrop/Presentation/MainScene/View/MainViewController.swift
StreetDrop/StreetDrop/Presentation/MainScene/ViewModel/MainViewModel.swift

close #127 
- 실시간으로 CLLocation 위치정보 갱신 및 사용자 오버레이 UI 위치 변경
- 메인화면 ViewDidLoad 시, 한번 현재위치로 카메라 이동

✨실시간으로 CLLocation 위치정보 사용자 오버레이 UI 위치 갱신

---

StreetDrop/StreetDrop.xcodeproj/project.pbxproj
StreetDrop/StreetDrop/Data/DataMapping/VillageName/VillageNameResponseDTO.swift
StreetDrop/StreetDrop/Data/Repositories/Protocol/SearchingMusic/SearchingMusicRepository.swift
StreetDrop/StreetDrop/Data/Repositories/SearchingMusic/DefaultSearchingMusicRepository.swift
StreetDrop/StreetDrop/Network/NetworkManager.swift
StreetDrop/StreetDrop/Network/NetworkService.swift
StreetDrop/StreetDrop/Presentation/MainScene/View/MainViewController.swift
StreetDrop/StreetDrop/Presentation/MainScene/ViewModel/MainViewModel.swift
StreetDrop/StreetDrop/Presentation/SearchingMusicScene/Model/SearchingMusicModel.swift
StreetDrop/StreetDrop/Presentation/SearchingMusicScene/ViewModel/SearchingMusicViewModel.swift

close #143 
- 메인화면의 드랍버튼 누를떄의 현재위치 좌표값으로, 음악검색화면 viewDidload 시 "/geo/reverse-geocode" API를 통해 현재 위치 주소를 가져오도록 함
- 드랍화면에서만 현재 위치 주소를 사용하기 때문
- 드랍화면의 주소가 메인화면의 드랍하기 버튼 눌렀을때의 좌표에 대한 주소인지 확인

🐛드랍하기 화면에서 주소가 사용자 현재 위치가 아닌 사용자 카메라 위치로 뜨는 버그 해결

---

StreetDrop/StreetDrop/Presentation/CommunityView/ViewModel/CommunityViewModel.swift
StreetDrop/StreetDrop/Presentation/MainScene/View/MainViewController.swift
StreetDrop/StreetDrop/Presentation/MainScene/ViewModel/MainViewModel.swift

close #173 
- POI Marker 지도에 표시하기 전에, 지도에 표시되었던 POI Marker들 삭제
- POI 엔티티가 아닌 NMFMarker에 대해서는 poi -> poiMarker로 개명
- 커뮤니티 화면에서 음악 삭제후, 메인화면으로 돌아올때 삭제한 음악 지도에서 사라졌는지 확인

🐛: 메인화면 ViewWillAppear시 지도의 이전 마커들 삭제 후, 최신 POI에 대해 마커들 나타냄

---

StreetDrop/StreetDrop/Presentation/MainScene/ViewModel/MainViewModel.swift

close #204 
- 대한민국 전체 poi 나타나도록 수정

🐛대한민국 전체 poi 나타나도록 수정

---

StreetDrop/StreetDrop/Presentation/MainScene/View/MainViewController.swift

close #184 
- 지도 줌 아웃 레벨, 지도 영역 제한

✨지도 줌 아웃 레벨, 지도 영역 제한

---

StreetDrop/StreetDrop/Presentation/CommunityView/View/CommunityViewController.swift
StreetDrop/StreetDrop/Presentation/MusicDropView/View/MusicDropViewController.swift
StreetDrop/StreetDrop/Presentation/Utils/Extension/UIcolor+.swift

close #215 
QA 노션 링크 첨부합니다
[1. 드랍텍스트 40자 제한 표시안뜸](https://www.notion.so/depromeet/40-a03cf11400e646b29f0629676b62cc60?pvs=4)
[2. 드랍텍스트 복붙하면 무제한 가능](https://www.notion.so/depromeet/88707256ad5143bf936c2ebf8eeec614?pvs=4)
[3. 커뮤니티 노래명 긴 경우 말줄임표 추가](https://www.notion.so/depromeet/8bc5965eab4a4beea6e2e0902a2a7b25?pvs=4)

🐛 1차 배포후 나온 QA해결 (드랍화면, 커뮤니티화면)

---

StreetDrop/StreetDrop.xcodeproj/project.pbxproj

👷버전업 1.0.2(빌드번호 1) -> 1.0.2(빌드번호 2)

👷버전업 1.0.2(빌드번호 1) -> 1.0.2(빌드번호 2)

---

StreetDrop/StreetDrop.xcodeproj/project.pbxproj
StreetDrop/StreetDrop/Data/Repositories/Setting/DefaultSettingsRepository.swift
StreetDrop/StreetDrop/Domain/UseCase/SettingsUseCase.swift
StreetDrop/StreetDrop/Presentation/Settings/ViewModel/SettingsViewModel.swift

close #231 
설정화면 유스케이스 리팩토링
SettingsViewModel -> SettingsUseCase로 변경 및 UseCase에 위임
DefaultSettingsViewModel -> DefaultSettingsUseCase로 변경

♻️ 설정화면 유스케이스 리팩토링

---

StreetDrop/StreetDrop.xcodeproj/project.pbxproj
StreetDrop/StreetDrop/Util/Extensions/UINavigation+Gesture.swift

close #151 
- 네비게이션 스와이프 백 제스쳐 추가

✨#151: 네비게이션 스와이프 백 제스쳐 추가

---

StreetDrop/StreetDrop/Presentation/MyPage/View/MyPageViewController.swift

close #252 
- 마이페이지 진입 시 앱 충돌 처리 
- 하나의 RxDataSource 를 두 개의 UITableView 에 바인딩하여 발생하는 오류로 파악됨.
->  RxDataSource 분리를 통해 해결함.
- 10월 29일 19시부터 31일 19시까지 내부 테스트 완료
- 메인페이지 진입 후 하단 마이페이지 버튼을 통해 진입했을 때 충돌이 발생하지 않는지 확인

🐛#252: 마이페이지 진입 시 앱 충돌 이슈 처리

---

StreetDrop/StreetDrop.xcodeproj/project.pbxproj
StreetDrop/StreetDrop/Data/DataMapping/MyDropList/MyDropListResponseDTO+Mapping.swift
StreetDrop/StreetDrop/Data/DataMapping/MyLikeList/MyLikeListResponseDTO+Mapping.swift
StreetDrop/StreetDrop/Data/DataMapping/SingleMusic/SingleMusicResponseDTO.swift
StreetDrop/StreetDrop/Data/Repositories/MyPage/DefaultMyPageRepository.swift
StreetDrop/StreetDrop/Data/Repositories/Protocol/MyPage/MyPageRepository.swift
StreetDrop/StreetDrop/Network/NetworkManager.swift
StreetDrop/StreetDrop/Network/NetworkService.swift
StreetDrop/StreetDrop/Presentation/MyPage/Model/Entites/MyMusic.swift
StreetDrop/StreetDrop/Presentation/MyPage/Model/MyPageModel.swift
StreetDrop/StreetDrop/Presentation/MyPage/View/MyPageType.swift
StreetDrop/StreetDrop/Presentation/MyPage/View/MyPageViewController.swift
StreetDrop/StreetDrop/Presentation/MyPage/ViewModel/MyPageViewModel.swift

close #254 
- 마이페이지 드랍한 또는 좋아요한 음악 선택 시 상세 페이지 진입 기능
- 음악 단건 조회 API 추가
- Firebase 패키지 업데이트
- 마이페이지에서 드랍한 또는 좋아요한 음악 선택했을 때 상세 페이지 진입 확인 및 상세 페이지에서 기능 작동되는 것 확인

✨#254: 마이페이지 드랍한 또는 좋아요한 음악 선택 시 상세 페이지 진입 기능

---

StreetDrop/StreetDrop.xcodeproj/project.pbxproj
StreetDrop/StreetDrop/Data/PersistentStorages/UserDefaultsStorage/Protocol/RecentMusicQueriesStorage.swift
StreetDrop/StreetDrop/Data/Repositories/Protocol/SearchingMusic/SearchingMusicRepository.swift
StreetDrop/StreetDrop/Data/Repositories/SearchingMusic/DefaultSearchingMusicRepository.swift
StreetDrop/StreetDrop/Domain/Entity/RecommendMusic.swift
StreetDrop/StreetDrop/Domain/UseCase/SearchMusicUsecase.swift
StreetDrop/StreetDrop/Network/NetworkManager.swift
StreetDrop/StreetDrop/Network/NetworkService.swift
StreetDrop/StreetDrop/Presentation/MusicDropView/ViewModel/MusicDropViewModel.swift
StreetDrop/StreetDrop/Presentation/SearchingMusicScene/View/LeftAlignedCollectionViewFlowLayout.swift
StreetDrop/StreetDrop/Presentation/SearchingMusicScene/View/RecommendKeywordItemCell.swift
StreetDrop/StreetDrop/Presentation/SearchingMusicScene/View/RecommendMusicSearchCollectionView.swift
StreetDrop/StreetDrop/Presentation/SearchingMusicScene/View/SearchingMusicViewController.swift
StreetDrop/StreetDrop/Presentation/SearchingMusicScene/ViewModel/SearchingMusicViewModel.swift

서버에서 오는 추천 타이틀 문구와 추천 키워드에 대한 기능 개발 건 입니다
추천 타이틀 문구는 default/highlight 값에 따라 색상 값이 변경
추천 키워드 값은 default/highlight 값에 따라 bg color 및 font color 변경
close #257 
추천 타이틀, 추천 키워드 기능 개발

✨#257: 추천 타이틀, 추천 키워드 기능 개발

---

StreetDrop/StreetDrop.xcodeproj/project.pbxproj
StreetDrop/StreetDrop/Data/PersistentStorages/UserDefaultsStorage/Protocol/MyInfoStorage.swift
StreetDrop/StreetDrop/Data/PersistentStorages/UserDefaultsStorage/RecentMusicSearch/UserDefaultsMyInfoStorage.swift
StreetDrop/StreetDrop/Data/Repositories/DefaultMyInfoRepository.swift
StreetDrop/StreetDrop/Data/Repositories/Protocol/MyInfo/MyInfoRepository.swift
StreetDrop/StreetDrop/Domain/UseCase/DefaultMyInfoUseCase.swift
StreetDrop/StreetDrop/Domain/UseCase/MyInfoUseCase.swift
StreetDrop/StreetDrop/Presentation/MainScene/View/MainViewController.swift
StreetDrop/StreetDrop/Presentation/MainScene/ViewModel/MainViewModel.swift
StreetDrop/StreetDrop/Presentation/Utils/BubbleCommentView.swift
StreetDrop/StreetDrop/Util/Constant/UserDefaultKey.swift

close #259 
- 처음 설치한 유저에게 일회성으로 드랍하세요 코멘트 박스 표시
- 1.0.8 (3) 참고

✨드랍해보세요 코멘트 박스 기능 개발

---

StreetDrop/StreetDrop/Presentation/MusicDropView/View/MusicDropViewController.swift

close #264 
- 키패드 엔터의 기능을 줄넘김에서 키패드 내리는 기능으로 변경

✨#264: 뮤직 드랍 페이지 키패드 엔터 기능 변경

---

StreetDrop/StreetDrop/Presentation/CommunityView/View/CommunityViewController.swift
StreetDrop/StreetDrop/Resource/Info.plist

close #265 
- Spotify 바로 듣기 기능 로직 추가
- Spotify 스킴 추가

🐛 #265: Spotify 스킴 및 앱 열기 로직 추가

---

StreetDrop/StreetDrop.xcodeproj/project.pbxproj
StreetDrop/StreetDrop/Data/DataMapping/MyInfo/UserCircleRadiusResponseDTO.swift
StreetDrop/StreetDrop/Data/Repositories/DefaultMyInfoRepository.swift
StreetDrop/StreetDrop/Data/Repositories/Protocol/MyInfo/MyInfoRepository.swift
StreetDrop/StreetDrop/Domain/UseCase/DefaultFetchingUserCircleRadiusUsecase.swift
StreetDrop/StreetDrop/Domain/UseCase/FetchingUserCircleRadiusUsecase.swift
StreetDrop/StreetDrop/Network/NetworkManager.swift
StreetDrop/StreetDrop/Network/NetworkService.swift
StreetDrop/StreetDrop/Presentation/MainScene/View/MainViewController.swift
StreetDrop/StreetDrop/Presentation/MainScene/ViewModel/MainViewModel.swift
StreetDrop/StreetDrop/Presentation/Splash/View/SplashViewController.swift
StreetDrop/StreetDrop/Presentation/Splash/ViewModel/SplashViewModel.swift

close #272 
- 서버로 부터 원반경 Radius가져와 메인화면에서 해당 Radius만큼 원반경 지정

✨레벨에 따른 사용자 원반경 변경

---

StreetDrop/Podfile
StreetDrop/Podfile.lock
StreetDrop/StreetDrop.xcodeproj/project.pbxproj
StreetDrop/StreetDrop/Application/AppDelegate.swift
StreetDrop/StreetDrop/Presentation/SearchingMusicScene/View/SearchingMusicViewController.swift
StreetDrop/StreetDrop/Resource/Info.plist
StreetDrop/StreetDrop/Util/Constant/GADUnitID.swift

close #274 
- 음악 검색 페이지 하단 광고 배너 추가

✨음악 검색페이지 광고 배너 추가

---

StreetDrop/StreetDrop/Application/AppDelegate.swift
StreetDrop/StreetDrop/Resource/Info.plist

close #276 
iOS14 이상 버전 IDFA 허용 추가 및 애드몹 광고 관련 설정

✨#276: Admob 광고 관련 추가 설정

---

StreetDrop/StreetDrop/Application/SceneDelegate.swift
StreetDrop/StreetDrop/Presentation/CommunityView/View/CommunityViewController.swift
StreetDrop/StreetDrop/Util/Extensions/String+Base64.swift

close https://github.com/depromeet/street-drop-iOS/issues/278
- url 인코딩 처리 방식 수정
- 앱 실행후 공유하기로 공유해보기

🐛 #278: 딥링크 url 처리 방식 변경

---

StreetDrop/StreetDrop.xcodeproj/project.pbxproj
StreetDrop/StreetDrop/Data/DataMapping/MyLevel/LevelPolicyResponseDTO.swift
StreetDrop/StreetDrop/Data/DataMapping/MyLevel/MyLevelProgressResponseDTO.swift
StreetDrop/StreetDrop/Data/Repositories/MyPage/DefaultMyPageRepository.swift
StreetDrop/StreetDrop/Data/Repositories/Protocol/MyPage/MyPageRepository.swift
StreetDrop/StreetDrop/Domain/Entity/LevelPolicy.swift
StreetDrop/StreetDrop/Domain/Entity/MyLevelProgress.swift
StreetDrop/StreetDrop/Domain/UseCase/DefaultFetchingLevelPolicyUseCase.swift
StreetDrop/StreetDrop/Domain/UseCase/FetchingLevelPolicyUseCase.swift
StreetDrop/StreetDrop/Network/NetworkManager.swift
StreetDrop/StreetDrop/Network/NetworkService.swift
StreetDrop/StreetDrop/Presentation/CommunityView/View/CommunityViewController.swift
StreetDrop/StreetDrop/Presentation/MusicDropView/View/MusicDropViewController.swift
StreetDrop/StreetDrop/Presentation/MyPage/Model/MyPageModel.swift
StreetDrop/StreetDrop/Presentation/MyPage/View/GradientProgressBar.swift
StreetDrop/StreetDrop/Presentation/MyPage/View/LevelUpGuideView.swift
StreetDrop/StreetDrop/Presentation/MyPage/View/MyPageViewController.swift
StreetDrop/StreetDrop/Presentation/MyPage/ViewModel/MyPageViewModel.swift
StreetDrop/StreetDrop/Presentation/Splash/View/SplashViewController.swift
StreetDrop/StreetDrop/Presentation/Utils/AlertViewController.swift
StreetDrop/StreetDrop/Presentation/Utils/Alertable.swift
StreetDrop/StreetDrop/Presentation/Utils/Extension/NSMutableAttributedString+.swift
StreetDrop/StreetDrop/Presentation/Utils/Extension/UIButton+.swift
StreetDrop/StreetDrop/Presentation/Utils/Extension/UILabel+applyGradient.swift
StreetDrop/StreetDrop/Presentation/Utils/Extension/UIView+RoundCorners.swift
StreetDrop/StreetDrop/Presentation/Utils/Extension/UIcolor+.swift
StreetDrop/StreetDrop/Presentation/Utils/LevelPolicyPopUpViewController.swift
StreetDrop/StreetDrop/Presentation/Utils/LevelPolicySubView.swift

close #281 
- 마이페이지 레벨 드랍 액션 유도 및 가이드 뷰 추가
- 레벨 등급 안내 팝업 추가
- 기존 팝업뷰 개선(기존 컨펌팝업에 알러트팝업 추가)

마이페이지 드랍 액션 유도 및 가이드 뷰 추가
